config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root 'home#index'
  resources :contacts do
    member do
      post :send_document
    end
  end
  resources :email_lists do
    member do
      post :send_document
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
# app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
    has_and_belongs_to_many :email_lists
    belongs_to :user
  end

app/models/email_list.rb
# app/models/email_list.rb
class EmailList < ApplicationRecord
  # Relações
  belongs_to :user
  has_and_belongs_to_many :contacts

  # Validações
  validates :name, presence: true
  validates :contact_ids, presence: true


end

app/models/email_lists_contact.rb
class EmailListsContact < ApplicationRecord
  belongs_to :email_list
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :email_lists
  # Associação com contatos
  has_many :contacts, dependent: :destroy
  has_many :email_lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authorize_contact_access, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      @contacts = current_user.contacts.order(updated_at: :desc, created_at: :desc)
      if @contacts.empty?
        redirect_to new_contact_path
      end
    else
      redirect_to new_user_session_path
    end
  end

  def show
  end

  def new
    @contact = current_user.contacts.build
  end

  def edit
  end


  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      respond_to do |format|
        format.html { redirect_to @contact, notice: 'Contato criado com sucesso.' }
        format.turbo_stream { redirect_to @contact }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("error-messages", partial: "contacts/error_messages", locals: { contact: @contact }) }
      end
    end
  end




  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url
  end

  def send_document
    @contact = current_user.contacts.find(params[:id])
    document = params[:document]
    if document.present?
      DocumentMailer.send_document(@contact, document).deliver_now
      redirect_to @contact
    else
      redirect_to @contact
    end
  end

  private

  def set_contact
    @contact = current_user.contacts.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email)
  end

  def authorize_contact_access
    redirect_to root_path, alert: 'Access denied.' unless current_user.contacts.include?(@contact)
  end
end

app/controllers/email_lists_controller.rb
class EmailListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_email_list, only: [:show, :edit, :update, :destroy, :send_document]
  before_action :authorize_email_list_access, only: [ :show, :edit, :update, :destroy]

  def index
     @email_lists = current_user.email_lists.order(updated_at: :desc)
  
  end

  def show

  end

  def new
    @email_list = EmailList.new
    @contacts = current_user.contacts

  end

  def edit
    @email_list = EmailList.find(params[:id])
    @contacts = current_user.contacts
    @selected_contacts = @email_list.contacts
  end



  def create
    @email_list = current_user.email_lists.build(email_list_params)
    if @email_list.save
      respond_to do |format|
        format.html { redirect_to  @email_list }
        format.turbo_stream { redirect_to email_lists_path(created: true) }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("error-messages", partial: "email_lists/error_messages", locals: { email_list: @email_list }) }
      end
    end
  end



  def update
    if @email_list.update(email_list_params)
      redirect_to email_lists_path
    else
      @contacts = current_user.contacts.order(updated_at: :desc, created_at: :desc)
      render :edit
    end
  end


  def destroy
    @email_list.destroy
    redirect_to email_lists_url
  end

  def send_document
    text_email_content = @email_list.text_email
    if params[:documents].present? && params[:documents].is_a?(Array) # Verifica se há documentos enviados e se é um array
      begin
        # Coleta todos os documentos em um array
        documents = params[:documents].map do |document_file|
          next if document_file.blank? # Ignora arquivos vazios

          # Cria um novo arquivo a partir do upload
          ActionDispatch::Http::UploadedFile.new(
            tempfile: document_file.tempfile,
            filename: document_file.original_filename,
            content_type: document_file.content_type
          )
        end.compact # Remove nils do array

        # Envia o e-mail para cada contato com todos os documentos anexados
        @email_list.contacts.each do |contact|
          DocumentMailer.send_documents(contact, documents, text_email_content).deliver_now
        end

        flash[:notice] = "Sua lista de e-mails foi enviada com sucesso!"
      rescue StandardError => e
        # flash[:alert] = "Falha ao enviar documentos: #{e.message}"
      end
    else
      # sflash[:alert] = "Nenhum documento foi enviado."
    end
    redirect_to @email_list
  end




  private

  def set_email_list
    @email_list = current_user.email_lists.find(params[:id])
  end

  def email_list_params
    params.require(:email_list).permit(:name, :document, :send_date, :text_email, contact_ids: [])
  end

  def authorize_email_list_access
    redirect_to root_path, alert: 'Acesso negado.' unless current_user.email_lists.include?(@email_list)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contacts_helper.rb
module ContactsHelper

end

app/helpers/email_lists_helper.rb
module EmailListsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/edit.html.erb
<div class="container-fluid">
  <div class="row vh-100">
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 10rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h2 class="text-center">Editar seu Contato</h2>
        <p class="text-center"><strong>Aqui você edita um contato!</strong></p>
        <p class="text-center">Edite o nome ou email do contato.</p>

      </div>
    </div>
    <div class="col-md-8 d-flex justify-content-center align-items-center" style="height: 100vh;">
      <div style="max-width: 400px; width: 100%; border: 1px solid black;" class="rounded p-4 shadow-sm bg-light">
        <h1 class="text-center">Editar Contato</h1>

        <%= form_with(model: @contact, local: true) do |form| %>


          <div class="mb-3">
            <%= form.label :name, "Nome", class: "form-label" %>
            <%= form.text_field :name, class: "form-control form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :email, "Email", class: "form-label" %>
            <%= form.email_field :email, class: "form-control form-control" %>
          </div>

          <div class="d-grid gap-2">
            <%= form.submit "Salvar", class: "btn btn-primary btn-block rounded-pill" %>
            <%= link_to 'Voltar', contacts_path, class: "btn btn-outline-secondary mt-3 d-block w-100" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<section class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div style="max-width: 400px; width: 100%;" class="rounded p-4 shadow-sm bg-light">
    <h1 class="text-center">Editar Contato</h1>

    <% if @contact.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @contact, local: true) do |form| %>
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control" %>
      </div>

      <div class="text-center">
        <%= form.submit "Salvar", class: "btn btn-primary mt-3 d-block w-100" %>
      </div>
    <% end %>

    <div class="text-center mt-3">
      <%= link_to 'Voltar', contacts_path, class: "btn btn-outline-secondary mt-3 d-block w-100" %>
    </div>
  </div>
</section>

app/views/contacts/index.html.erb
<div class="container-fluid">
  <div class="row vh-100">
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 10rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h2 class="text-center">Seus Contatos</h2>
        <p class="text-center"><strong>Aqui você verifica seus contatos!!!</strong></p>
        <p class="text-center">Insira, Edite ou Exclua ...</p>
      </div>
    </div>
    <div class="col-md-8 d-flex justify-content-center align-items-center" style="height: 100vh;">
      <div style="max-width: 900px; width: 100%;" class="rounded p-4 shadow-sm bg-light">

        
          <div class="d-flex justify-content-between mb-3">
            <%= link_to 'Novo Contato', new_contact_path, class: "btn btn-primary" %>
          </div>

          <div style="max-height: 399px; overflow-y: auto;">
            <table class="table table-hover table-striped table-bordered text-center">
              <thead class="thead-dark sticky-header">
              <tr>
                <th>Nome</th>
                <th>Email</th>
                <th colspan="3">Acões</th>
              </tr>
              </thead>
              <tbody>
              <% @contacts.each do |contact| %>
                <tr>
                  <td><%= contact.name %></td>
                  <td><%= contact.email %></td>
                  <td><%= link_to 'Mostrar', contact, class: "btn btn-sm btn-info" %></td>
                  <td><%= link_to 'Editar', edit_contact_path(contact), class: "btn btn-sm btn-primary" %></td>
                  <td><%= button_to 'Apagar', contact_path(contact), method: :delete, data: { turbo_confirm: 'Você deseja realmente excluir este contato?' }, class: 'btn btn-sm btn-danger' %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <br>
          <p><strong>Total de Contatos: <%= @contacts.count %></strong></p>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid">
  <div class="row vh-100">
    <!-- Div da esquerda para mensagens de erro -->
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 7rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h2 class="text-center">Cadastro de Contatos</h2>
        <p class="text-center"><strong>Aqui você cadastra um contato!</strong></p>
        <p class="text-center">Cadastre o nome e o email do contato de envio.</p>
      </div>


        <%= render 'contacts/error_messages', contact: @contact %>


    </div>

    <!-- Div da direita para o formulário -->
    <div class="col-md-8 d-flex justify-content-center align-items-center" style="height: 100vh;">
      <div style="max-width: 400px; width: 100%; border: 1px solid black;" class="rounded p-4 shadow-sm bg-light">
        <h1 class="text-center">Novo Contato</h1>

        <%= form_with model: @contact, local: true do |form| %>
          <div class="mb-3">
            <%= form.label :name, "Nome", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :email, "Email", class: "form-label" %>
            <%= form.email_field :email, class: "form-control" %>
          </div>

          <div class="d-grid gap-2">
            <%= form.submit "Salvar", class: "btn btn-primary btn-block rounded-pill" %>
            <%= link_to 'Voltar', contacts_path, class: "btn btn-outline-secondary mt-3 d-block w-100" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container-fluid">
  <div class="row vh-100">
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 10rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h2 class="text-center">Contato incluso!</h2>
        <p class="text-center">Aqui você verifica seu contato, já incluso para utilizar na sua lista de emails!</p>
        </div>
    </div>
    <div class="col-md-8 d-flex justify-content-center align-items-center" style="height: 100vh;">
      <section class="d-flex justify-content-center align-items-center" style="width: 100%;">
        <div style="max-width: 400px; width: 100%; border: 1px solid black;" class="rounded p-4 shadow-sm bg-light">
          <h1 class="text-center">Contato</h1>

          <% if @contact.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

              <ul>
                <% @contact.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <label class="form-label"><strong>Nome:</strong></label>
            <p><%= @contact.name %></p>
          </div>

          <div class="mb-3">
            <label class="form-label"><strong>Email:</strong></label>
            <p><%= @contact.email %></p>
          </div>

          <div class="d-grid gap-2">
            <%= link_to 'Editar', edit_contact_path(@contact), class: "btn btn-primary btn-block rounded-pill" %>
            <%= link_to 'Voltar', contacts_path, class: "btn btn-outline-secondary mt-3 d-block w-100" %>
          </div>
          <br>
          <div class="d-flex justify-content-between mb-3">
            <div class="w-100 text-center">
              <%= link_to 'Continuar Cadastrando ?', new_contact_path %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/email_lists/_error_messages.html.erb
<div id="error-messages">
  <% if @email_list.errors.any? %>
    <div style="max-width: 300px; width: 100%; margin-top: 1rem; border: 2px solid red;" class="rounded p-4 shadow-sm mx-auto">
      <h4 class="alert-heading">Erros:</h4>
      <ul>
        <% @email_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/email_lists/index.html.erb
<%= stylesheet_link_tag 'email_lists', media: 'all' %>

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">


  script>
  document.addEventListener("turbo:load", function() {
    if (!sessionStorage.getItem("reloaded")) {
      sessionStorage.setItem("reloaded", "true");
      location.reload(true);
    } else {
      sessionStorage.removeItem("reloaded");
    }
  });
</script>

 </head>
<body>

<div class="container-fluid">
  <div class="row vh-100">
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 10rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h1 class="text-center">Cadastro da Lista!</h1>
        <p class="text-center"><strong>Aqui você cadastra uma lista de emails!</strong></p>
        <p class="text-center">Cadastre o nome e adicione os contatos na lista.</p>
      </div>
    </div>
    
    
    <div class="col-md-8 d-flex justify-content-center align-items-center" style="height: 100vh;">
     <div style="max-width: 900px; width: 100%;" class="rounded p-4 shadow-sm bg-light">
     
        <div class="d-flex justify-content-between mb-3">
          <%= link_to 'Nova Lista de Emails', new_email_list_path, class: 'btn btn-primary' %>
        </div>

        <div style="max-height: 399px; overflow-y: auto;">
          <table class="table table-hover table-striped table-bordered text-center">
            <thead class="thead-dark sticky-header">
            <tr>
              <th>Nome</th>
              <th>Contatos</th>
              <th colspan="4">Ações</th>
            </tr>
            </thead>
            <tbody>
            <% @email_lists.each do |email_list| %>
              <tr>
                <td><%= email_list.name %></td>
                <td><%= email_list.contacts.size %></td>
                <% if email_list.contacts.present? %>
                  <td><%= link_to 'Enviar Lista', email_list, class: 'btn btn-sm btn-info' %></td>
                <% else %>
                  <td></td>
                <% end %>
                <td><%= link_to 'Editar', edit_email_list_path(email_list), class: 'btn btn-sm btn-primary' %></td>
                <td><%= button_to 'Apagar', email_list, method: :delete, data: { turbo_confirm: 'Você deseja realmente excluir esta Lista?' }, class: 'btn btn-sm btn-danger' %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <br>
        <p><strong>Total de Listas: <%= @email_lists.count %></strong></p>

      </div>
    </div>
  </div>

</div>

</body>
</html>

app/views/email_lists/show.html.erb
<%= stylesheet_link_tag 'email_lists', media: 'all' %>

<main class="container-fluid">
  <div class="row vh-100">
    <!-- Div da esquerda -->
    <div class="col-md-4 bg-dark text-white p-0">
      <div style="max-width: 300px; width: 100%; margin-top: 6rem; border: 2px solid yellow;" class="rounded p-4 shadow-sm mx-auto">
        <h2 class="text-center">Cadastro de Listas de Emails</h2>
        <p class="text-center"><strong>Aqui você cadastra uma lista de emails!</strong></p>
        <p class="text-center">Cadastre o nome e selecione os contatos para a lista de envio.</p>
        <!-- Botão para editar o texto do email -->
        <div class="text-center">
          <button id="edit-text-button" class="btn btn-warning mt-3" data-bs-toggle="modal" data-bs-target="#editTextModal">Editar Texto do Email</button>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <div style="max-width: 300px; width: 100%; margin-top: 1rem; border: 2px solid green;" class="rounded p-4 shadow-sm mx-auto">
          <h4 class="alert-heading">Aviso:</h4>
          <div>
            <%= flash[:notice] %>
          </div>
        </div>
      <% end %>

      <% if flash[:alert].present? %>
        <div style="max-width: 300px; width: 100%; margin-top: 1rem; border: 2px solid red;" class="rounded p-4 shadow-sm mx-auto">
          <h4 class="alert-heading">Erro:</h4>
          <div>
            <%= flash[:alert] %>
          </div>
        </div>
      <% end %>

    </div>

    <!-- Div da direita fixa na tela e ocupa o espaço restante -->
    <div class="col-md-8 d-flex justify-content-center align-items-start" style="height: 100%;">
      <div class="rounded p-4 shadow-sm bg-light" id="details-box">
        <br><br><br>
        <div class="mb-3 d-flex justify-content-between">
          <p><strong>Nome:</strong> <%= @email_list.name %></p>
          <p><strong>Data de Envio:</strong> <%= @email_list.send_date.present? ? @email_list.send_date.strftime("%d/%m/%Y %H:%M") : DateTime.current.strftime("%d/%m/%Y %H:%M") %></p>
        </div>

        <% if @email_list.contacts.any? %>
          <div class="table-responsive" style="height: 200px; overflow-y: scroll;">
            <table class="table table-hover table-striped table-bordered text-center">
              <thead class="thead-dark sticky-header">
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
              </tr>
              </thead>
              <tbody>
              <% @email_list.contacts.order(updated_at: :desc).each do |contact| %> <!-- Ordenando contatos por updated_at -->
                <tr>
                  <td><%= contact.name %></td>
                  <td><%= contact.email %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          <p class="text-center">Nenhum contato disponível.</p>
        <% end %>

        <br><br>
        <h5 class="mb-3">Enviar Documento</h5>

        <%= form_with url: send_document_email_list_path(@email_list), local: true, method: :post, multipart: true, id: "send-document-form" do |form| %>
          <div id="document-section" class="d-flex mb-3">
            <div class="me-2 flex-grow-1">
              <%= form.label :documents, "Selecione seus documentos para anexar", class: "form-label" %>
              <%= form.file_field :documents, accept: '.pdf,.doc,.odt', multiple: true, class: "form-control", id: "document-field" %>
            </div>
            <%= form.submit "Enviar Lista", class: "btn btn-warning align-self-end", id: "send-document-button" %>
          </div>
        
          <div id="success-message" class="alert alert-success d-none mt-3" role="alert">
          📩 Enviando a lista!
          </div>
        <% end %>

        <div class="mt-4">
          <%= link_to 'Editar', edit_email_list_path(@email_list), class: 'btn btn-primary me-2' %>
          <%= link_to 'Voltar', email_lists_path, class: 'btn btn-secondary' %>
        </div>
      </div>

      <!-- Div para edição de text_email -->
      <div class="details-box rounded p-4 shadow-sm bg-light d-none" id="text-email-box">
        <h4 class="text-center mb-4">Editar Texto do Email</h4>
        <%= form_with model: @email_list, url: @email_list.persisted? ? email_list_path(@email_list) : email_lists_path, local: true, method: @email_list.persisted? ? :patch : :post do |form| %>
          <div class="mb-3">
            <%= form.label :text_email, "Digite aqui seu texto personalizado!", class: "form-label" %>
            <%= form.text_area :text_email, value: @email_list.text_email, rows: 10, class: "form-control text-email-field" %>
       
            </div>
            <div class="text-center">
            <%= form.submit "Salvar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

      <!-- Modal para edição de text_email -->
      <div class="modal fade" id="editTextModal" tabindex="-1" aria-labelledby="editTextModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="editTextModalLabel">Texto do Email</h3>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= form_with model: @email_list, url: @email_list.persisted? ? email_list_path(@email_list) : email_lists_path, local: true, method: @email_list.persisted? ? :patch : :post do |form| %>
                <div class="mb-3">
                  <%= form.label :text_email, "Digite aqui seu texto personalizado!", class: "form-label" %>
                  <%= form.text_area :text_email, value: @email_list.text_email, rows: 10, class: "form-control text-email-field" %>
                </div>
                <div class="text-center">
                <%= form.submit "Salvar", class: "btn btn-primary" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</main>

<script>
    document.addEventListener("turbo:load", function() {
        const documentField = document.getElementById("document-field");
        const sendDocumentButton = document.getElementById("send-document-button");
        const selectedCountSpan = document.getElementById("selected-count");
        const checkboxes = document.querySelectorAll(".contact-checkbox");
        const selectAllCheckbox = document.getElementById("select-all");
        const form = document.getElementById("send-document-form");
        const successMessage = document.getElementById("success-message");
        const documentSection = document.getElementById("document-section");

 
    if (form && successMessage && documentSection) {
      form.addEventListener("submit", function(event) {
        // Mostrar a mensagem de sucesso
        successMessage.classList.remove("d-none");

        // Ocultar o componente de anexos
        documentSection.style.display = "none";

        // Desabilitar o botão de envio
        sendDocumentButton.disabled = true;
      });
    }

       // Desabilitar o botão de envio inicialmente
        sendDocumentButton.disabled = true;

        // Função para habilitar/desabilitar o botão de envio
        function toggleSendButton() {
            sendDocumentButton.disabled = documentField.files.length === 0;
        }

        // Adicionar evento de mudança ao campo de arquivo
        documentField.addEventListener("change", toggleSendButton);

        function updateSelectedCount() {
            const selectedCount = document.querySelectorAll(".contact-checkbox:checked").length;
            selectedCountSpan.textContent = `Contatos Selecionados: ${selectedCount}`;
        }

        function handleSelectAll() {
            const isChecked = selectAllCheckbox.checked;
            checkboxes.forEach(checkbox => {
                checkbox.checked = isChecked;
            });
            updateSelectedCount();
        }

        if (selectAllCheckbox) {
            selectAllCheckbox.addEventListener("change", handleSelectAll);
        }

        checkboxes.forEach(checkbox => {
            checkbox.addEventListener("change", updateSelectedCount);
        });

        updateSelectedCount();

        if (!sessionStorage.getItem("reloaded")) {
          sessionStorage.setItem("reloaded", "true");
          location.reload(true);
        } else {
          sessionStorage.removeItem("reloaded");
        }
        });

        
</script>

app/views/shared/_navbar.html.erb
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Lista de Emails</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="<%= contacts_path %>">Contatos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= email_lists_path %>">Listas</a>
          </li>

        </ul>

        <li class="nav-item">
        <span class="navbar-text user-email" style="color: yellow;">
    Bem-vindo, <%= current_user.email %>
</span>
        </li>
        <li class="nav-item">
          <%= button_to 'Sair', destroy_user_session_path, method: :delete, data: { turbo_confirm: 'Deseja Sair?', disable_with: 'Loading...' }, class: 'btn btn-outline-success ml-4' %>
        </li>



        <!--        <form class="d-flex" role="search">-->
<!--          <input class="form-control me-2" type="search" placeholder="Carro desejado..." aria-label="Search">-->
<!--          <button class="btn btn-outline-success" type="submit">Buscar</button>-->
<!--        </form>-->

        <%#= button_to 'Sair', destroy_user_session_path, method: :delete, data: { turbo_confirm: 'Deseja Sair?', disable_with: 'Loading...' }, class: 'btn btn-outline-success' %>





      </div>
    </div>
  </nav>
</header>